### ISSUE TITLE
 tab.element.length

### ISSUE THREAD

**Issue by Natega** [Geff974/projet5Repo#1]
https://github.com/Geff974/projet5Repo/blob/7d7766de8deee14258372a40b537be4a377ac909/app.js#L92

utilise un tab.element.length

**Comment by Geff974** [comment]
J'ai fais quelque petite changement. Ma fonction selectRandom ne fonctionnait pas bien car elle comptait les éléments d'un seul tableau et utilisé ce nombre pour sélectionner automatiquement les item, hors si le 3e tableau par exemple n'a que 3 element, la fonction n'en tenait pas compte.
